### ISSUE TITLE
The plugin doesn't install on ILIAS 5.2.20

### ISSUE THREAD

**Issue by dymitar** [studer-raimann/H5PCron#1]
The plugin doesn't install on ilias 5.2.20 with error 

Class 'ilCronHookPlugin' not found in /var/www/sportdepot/Customizing/global/plugins/Services/Cron/CronHook/H5PCron/classes/class.ilH5PCronPlugin.php:18

Adding
include_once("./Services/Cron/classes/class.ilCronHookPlugin.php");

solves the problem

**Comment by srgitlab** [comment]
@dymitar Thanks. I added this to the composer autoload
